# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Internal implementation of ldshrink
#'
#'
#'
ldshrink_cor <- function(genotype_data, anno, options) {
    .Call(`_ldshrink_ldshrink_cor`, genotype_data, anno, options)
}

#' Internal implementation of sample correlation
#'
#'
sample_cor <- function(genotype_data, anno, options) {
    .Call(`_ldshrink_sample_cor`, genotype_data, anno, options)
}

sorted_snp_df <- function(snp_info) {
    .Call(`_ldshrink_sorted_snp_df`, snp_info)
}

set_ld_region <- function(ld_regions, snp_info, assign_all = TRUE) {
    .Call(`_ldshrink_set_ld_region`, ld_regions, snp_info, assign_all)
}

#' Linear interpolation of genetic map values
NULL

#' @export
interpolate_genetic_map <- function(map, map_pos, target_pos, strict = TRUE, progress = FALSE) {
    .Call(`_ldshrink_interpolate_genetic_map`, map, map_pos, target_pos, strict, progress)
}

round_trip_skyline_t <- function(r_mat, to_t) {
    .Call(`_ldshrink_round_trip_skyline_t`, r_mat, to_t)
}

#' Determine whether 2 alleles are compatible
NULL

#' Determine whether 2 
NULL

#' @export
strand_flip <- function(ref_alt, reverse = FALSE) {
    .Call(`_ldshrink_strand_flip`, ref_alt, reverse)
}

#' @export
flip_alleles <- function(query_ref_alt, target_ref_alt) {
    .Call(`_ldshrink_flip_alleles`, query_ref_alt, target_ref_alt)
}

